version: "3.8"

services:
  frontend:
    container_name: frontend
    ports:
      - "3000:3000"
    build: frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules
    restart: always
    depends_on:
      - backend
  backend:
    container_name: backend
    ports:
      - "3001:3000"
    restart: always
    build: backend
    volumes:
      - ./backend:/home/app
      - /home/app/node_modules
    depends_on:
      - mongo
  mongo:
    container_name: mongo_public_api
    restart: always
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  data:
    name: mongo_db_data
